# in this directory, run the following command to build this builder
# $ gcloud builds submit . --config=cloudbuild.yaml
steps: 
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
  'build',
  '--tag=${_REGION}/${PROJECT_ID}/terraform:latest',
  '--tag=${_REGION}/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}',
  '--build-arg=TERRAFORM_VERSION=${_TERRAFORM_VERSION}',
  '--build-arg=TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}',
  '--build-arg=TERRAFORM_VALIDATOR_RELEASE=${_TERRAFORM_VALIDATOR_RELEASE}',
  '-'
  ]

  
